# Required
version: 2

build:
  os: ubuntu-20.04
  tools:
    python: "3.10"

mkdocs:
  configuration: docs/mkdocs.yml

# Optionally declare the Python requirements required to build your docs
python:
   install:
   - requirements: requirements.txt