site_name: PathIntegrate Docs

theme:
  name: "material"
  palette:
    primary: teal
    accent: teal

docs_dir: 'docs'
site_dir: 'site'

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
      - name: mermaid
        class: mermaid
        format: !!python/name:pymdownx.superfences.fence_code_format


extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js


plugins:
  - search
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          rendering:
            show_source: false
          options:
            docstring_style: google
            docstring_options:
              ignore_init_summary: no
            merge_init_into_class: no
            show_submodules: yes

nav:
  - Home: index.md
  # - Tutorials: 
  #   - tutorials.md
  #     - ssPA and SKLearn: 
  #       - gendocs_docs/reference/sklearn_sspa.md
  # - Reference:
  #   - gendocs_docs/reference/identifier_conversion.md
  #   - gendocs_docs/reference/download_pathways.md
  #   - gendocs_docs/reference/load_pathways.md
  #   - gendocs_docs/reference/utils.md
  #   - Pathway analysis:
  #     - gendocs_docs/reference/ORA.md
  #     - gendocs_docs/reference/GSEA.md
  #     - Single sample methods:
  #       - gendocs_docs/reference/SVD.md
  #       - gendocs_docs/reference/kPCA.md
  #       - gendocs_docs/reference/ssClustPA.md
  #       - gendocs_docs/reference/ssGSEA.md
  #       - gendocs_docs/reference/zscore.md
  
